version: "3.8"
services:
  finvisor_php:
    container_name: finvisor_php
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/api_finvisor
      - ./.env:/var/www/api_finvisor/.env
    restart: unless-stopped
    depends_on:
      finvisor_mysql:
        condition: service_healthy
    ports:
      - 9000:9000
      # - 8080:8080
    networks:
      - api_finvisor_backend

  finvisor_mysql:
    container_name: finvisor_mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - api_finvisor_backend

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8085:80
    environment:
      PMA_HOST: finvisor_mysql
      PMA_PORT: 3306
    depends_on:
      - finvisor_mysql
    networks:
      - api_finvisor_backend

volumes:
  mysql_data:

networks:
  api_finvisor_backend:
    driver: bridge
